version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://root:rootpassword@mongodb:27017/mydb
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb_data: